language: node_js
node_js:
  - node

install:
  - npm install
  - npm run build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  repo: hgiasac/hgiasac.github.io
  local-dir: dist
  on:
    branch: master

cache:
  yarn: true
